spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yoodonghyeon5017@gmail.com
    password: vimv offr klpr vmzm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

  application:
    name: StudyOn

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

#  servlet:
#    multipart:
#      maxFileSize: 10MB
#      maxRequestSize: 20MB

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}  # Hibernate 자동 DDL 생성 옵션

    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true  # SQL 쿼리 포맷팅 여부 - 프로덕션 환경에서는 보안, 성능 고려해서 사용
        use_sql_comments: true  # SQL 쿼리 주석 사용 여부 - 보안, 성능 이슈, (실행되는 JPQL을 볼 수 있다.)

logging.level:
  org.hibernate.SQL: debug  # Hibernate SQL 쿼리를 debug 레벨로 설정하여 로깅합니다.
  org.hibernate.orm.jdbc.bind: trace  # 스프링 부트 3.x, Hibernate 6.x에서 JDBC 바인딩을 trace 레벨로 설정합니다.

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    ttl: ${ACCESS_TOKEN_TTL}
  refresh-token:
    ttl: ${REFRESH_TOKEN_TTL}

server:
  port: ${SERVER_PORT}