### 인증 메일 발송
POST http://localhost:8080/api/v1/email/send
Content-Type: application/json

{
  "email":"{{email}}"
}

### 이메일 인증
PATCH http://localhost:8080/api/v1/email/verify
Content-Type: application/json

{
  "email":"{{email}}",
  "code":"LmI07kIC"
}