### 회원가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email":"{{email}}",
  "password":"{{password}}",
  "name":"{{name}}",
  "nickname":"{{nickname}}"
}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.log("Authorization: " + response.headers.valueOf("Authorization"));

    client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
    client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
%}

### 로그아웃
POST http://localhost:8080/api/v1/auth/logout
Authorization: {{Authorization}}
Content-Type: application/json

> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");
%}

### RefreshToken 재발급
POST http://localhost:8080/api/v1/auth/reissue
Content-Type: application/json

{
  "accessToken": "{{Authorization}}",
  "refreshToken": "{{RefreshToken}}"
}

### 팔로우 추가
POST http://localhost:8080/api/v1/users/follow/3
Content-Type: application/json
Authorization: {{Authorization}}

{
}

### 팔로우 삭제
DELETE http://localhost:8080/api/v1/users/follow/3
Content-Type: application/json
Authorization: {{Authorization}}

{

}

### 팔로잉 목록 조회
GET http://localhost:8080/api/v1/users/follow/5/following
Content-Type: application/json
Authorization: {{Authorization}}

{

}

### 팔로워 목록 조회
GET http://localhost:8080/api/v1/users/follow/2/followers
Content-Type: application/json
Authorization: {{Authorization}}

{

}